// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYyMkf7T2Kq1uscdLOZZGDSIaXoViLDFY',
    appId: '1:258879054493:web:3fe37e946b85c7c787aa74',
    messagingSenderId: '258879054493',
    projectId: 'stylishapp-d6777',
    authDomain: 'stylishapp-d6777.firebaseapp.com',
    storageBucket: 'stylishapp-d6777.appspot.com',
    measurementId: 'G-ZE2012WHQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJpYF7F5n_WfvheqcEBeeDOtflXf-QxU',
    appId: '1:258879054493:android:e5930351507ace8c87aa74',
    messagingSenderId: '258879054493',
    projectId: 'stylishapp-d6777',
    storageBucket: 'stylishapp-d6777.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1s9xJ9J4iLbl1s4tzjQhdKztzVgge8w',
    appId: '1:258879054493:ios:b79abcefb3fe908287aa74',
    messagingSenderId: '258879054493',
    projectId: 'stylishapp-d6777',
    storageBucket: 'stylishapp-d6777.appspot.com',
    iosClientId: '258879054493-6ns96cjnp580jt72rtkpqqd7h83frglm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn1s9xJ9J4iLbl1s4tzjQhdKztzVgge8w',
    appId: '1:258879054493:ios:b79abcefb3fe908287aa74',
    messagingSenderId: '258879054493',
    projectId: 'stylishapp-d6777',
    storageBucket: 'stylishapp-d6777.appspot.com',
    iosClientId: '258879054493-6ns96cjnp580jt72rtkpqqd7h83frglm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylishApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYyMkf7T2Kq1uscdLOZZGDSIaXoViLDFY',
    appId: '1:258879054493:web:ce5af853a8278acd87aa74',
    messagingSenderId: '258879054493',
    projectId: 'stylishapp-d6777',
    authDomain: 'stylishapp-d6777.firebaseapp.com',
    storageBucket: 'stylishapp-d6777.appspot.com',
    measurementId: 'G-XPL8YXHS8M',
  );
}
